import { useState, useEffect, useRef, useMemo } from 'react';
import ForceGraph2D from 'react-force-graph-2d';
import { buildNetworkGraph } from '../../utils/graphUtils';
import { hudAudio } from '../../utils/hudAudio';

export default function NetworkGraphPanel({ target }) {
  const containerRef = useRef(null);
  const graphRef = useRef(null);
  
  // Dimensions and standard states
  const [dims, setDims] = useState({ w: 400, h: 300 });
  const [selectedNode, setSelectedNode] = useState(null);
  const [hoverNode, setHoverNode] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [showSearchDropdown, setShowSearchDropdown] = useState(false);
  const [threatFilter, setThreatFilter] = useState('ALL');

  // Dynamic Layouts Mode
  const [layoutMode, setLayoutMode] = useState('organic'); // organic, hierarchical, circular

  // Annotations
  const [annotations, setAnnotations] = useState({}); // { [nodeId]: { flag, note } }

  // Bulk Selection Set
  const [selectedNodeIds, setSelectedNodeIds] = useState(new Set());

  // Entity Spawner Palette active tool
  const [activeSpawnType, setActiveSpawnType] = useState(null); // 'domain', 'ip', 'email', 'phone'

  // Context Menu state
  const [contextMenu, setContextMenu] = useState(null); // { x, y, node }
  const [loadingNodeIds, setLoadingNodeIds] = useState(new Set()); // Tracks active transforms

  // Defensive load initial dataset
  const initialData = useMemo(() => {
    if (!target) return { nodes: [], links: [] };
    return buildNetworkGraph(target);
  }, [target]);

  const [graphState, setGraphState] = useState({ nodes: [], links: [] });

  // Native ResizeObserver for zero-clipping canvas layout stretching
  useEffect(() => {
    if (!containerRef.current) return;

    const observer = new ResizeObserver((entries) => {
      if (!entries || entries.length === 0) return;
      const { width, height } = entries[0].contentRect;
      if (width > 0 && height > 0) {
        setDims({ w: width, h: height });
      }
    });

    observer.observe(containerRef.current);
    return () => observer.disconnect();
  }, []);

  // 100% Bulletproof getSeverity (Safely guards .toLowerCase() from throwing TypeErrors)
  const getSeverity = (label) => {
    if (!label || typeof label !== 'string') return 'LOW';
    const txt = label.toLowerCase();
    if (txt.includes('ssh') || txt.includes('open') || txt.includes('breach') || txt.includes('old') || txt.includes('vulnerability')) {
      return 'HIGH';
    }
    if (txt.includes('resolves') || txt.includes('github') || txt.includes('reliance') || txt.includes('carrier') || txt.includes('valid')) {
      return 'INFO';
    }
    return 'LOW';
  };

  // Physics force tuning with strict functional checking
  useEffect(() => {
    if (graphRef.current && typeof graphRef.current.d3Force === 'function') {
      const chargeForce = graphRef.current.d3Force('charge');
      if (chargeForce && typeof chargeForce.strength === 'function') {
        chargeForce.strength(-600); // Massive repulsion to push large boxes apart
      }
      const linkForce = graphRef.current.d3Force('link');
      if (linkForce && typeof linkForce.distance === 'function') {
        linkForce.distance(100);    // Extends link connector lengths
      }
    }
  }, [graphState]);

  // Handle layout coordinate mapping with active pipeline links
  const applyLayoutEngine = (mode, nodesList, linksList) => {
    const nodesSource = initialData?.nodes || [];
    const activeLinks = linksList || [];

    if (mode === 'organic') {
      // Unpin nodes so physics can float them dynamically
      nodesList.forEach(node => {
        if (node.group === 1) {
          node.fx = 0; node.fy = 0; // Keep root anchored
        } else {
          node.fx = null; node.fy = null;
        }
      });
    } 
    else if (mode === 'circular') {
      // Use the precise wide-radial coordinates generated by graphUtils.js
      nodesList.forEach((node, idx) => {
        const original = nodesSource.find(n => n.id === node.id);
        if (original) {
          node.fx = original.fx;
          node.fy = original.fy;
        } else {
          // Manually created nodes distributed symmetrically on outer radius
          const angle = (idx / nodesList.length) * Math.PI * 2;
          node.fx = Math.cos(angle) * 320;
          node.fy = Math.sin(angle) * 320;
        }
      });
    } 
    else if (mode === 'hierarchical') {
      const modules = nodesList.filter(n => n.group === 2);
      const findings = nodesList.filter(n => n.group === 3);

      // Level 1: Root Node (Target.com) centered at the top
      nodesList.forEach(node => {
        if (node.group === 1) {
          node.fx = 0; node.fy = -160;
        }
      });

      // Level 2: Modules spread out horizontally based on available container width
      const usableWidth = Math.max(500, dims.w - 120);
      const modSpacing = usableWidth / Math.max(1, modules.length - 1);
      
      modules.forEach((mod, idx) => {
        mod.fx = -usableWidth / 2 + idx * modSpacing;
        mod.fy = -40;
      });

      // --- CRASH-PROOF & PIPELINE SYNC PARENT LOOKUP ---
      // We map parent relationships directly using the live links array passed to this function
      findings.forEach(find => {
        const parentLink = activeLinks.find(l => {
          const targetId = typeof l.target === 'object' ? l.target.id : l.target;
          return targetId === find.id;
        });

        if (parentLink) {
          const sourceId = typeof parentLink.source === 'object' ? parentLink.source.id : parentLink.source;
          find.parentId = sourceId;
        }
      });

      // Level 3: Vertical Column Stacking (Completely prevents overlapping!)
      modules.forEach(mod => {
        const childFindings = findings.filter(f => f.parentId === mod.id);
        if (childFindings.length === 0) return;

        childFindings.forEach((child, childIdx) => {
          child.fx = mod.fx; // Align exactly centered below parent module
          child.fy = 15 + childIdx * 25; // Stack vertically downwards
        });
      });

      // Level 4: Dynamically generated grandchildren centered below parent findings
      findings.forEach(find => {
        const grandChildren = nodesList.filter(n => {
          const parentLink = activeLinks.find(l => {
            const targetId = typeof l.target === 'object' ? l.target.id : l.target;
            const sourceId = typeof l.source === 'object' ? l.source.id : l.source;
            return targetId === n.id && sourceId === find.id;
          });
          return parentLink !== undefined;
        });

        if (grandChildren.length === 0) return;

        grandChildren.forEach((gChild, gIdx) => {
          gChild.fx = find.fx + 20; // Slightly offset to the right
          gChild.fy = find.fy + 12 + gIdx * 20; // Stack below parent finding
        });
      });
    }
  };

  // Reset and load graph safely
  useEffect(() => {
    if (!initialData || !initialData.nodes) return;

    // Copy initial circular locked coords into start x/y coordinates safely
    const clonedNodes = initialData.nodes.map(n => {
      const startX = n.fx !== undefined && n.fx !== null ? n.fx : 0;
      const startY = n.fy !== undefined && n.fy !== null ? n.fy : 0;
      return {
        ...n,
        x: n.x !== undefined ? n.x : startX,
        y: n.y !== undefined ? n.y : startY,
        fx: layoutMode === 'organic' ? (n.group === 1 ? 0 : null) : n.fx,
        fy: layoutMode === 'organic' ? (n.group === 1 ? 0 : null) : n.fy
      };
    });
    const clonedLinks = (initialData.links || []).map(l => ({ ...l }));
    
    applyLayoutEngine(layoutMode, clonedNodes, clonedLinks); // Direct Links pipeline injection

    setGraphState({ nodes: clonedNodes, links: clonedLinks });
    setSelectedNode(null);
    setSelectedNodeIds(new Set());
    setContextMenu(null);
    setActiveSpawnType(null);
  }, [initialData, target]);

  // Handle layout switches
  const handleLayoutChange = (mode) => {
    hudAudio.playSweep();
    setLayoutMode(mode);
    
    const updatedNodes = graphState.nodes.map(n => ({ ...n }));
    const activeLinks = graphState.links || [];
    applyLayoutEngine(mode, updatedNodes, activeLinks);
    
    setGraphState(prev => ({ ...prev, nodes: updatedNodes }));
    
    // Reheat physics simulation safely
    if (graphRef.current && typeof graphRef.current.d3ReheatSimulation === 'function') {
      graphRef.current.d3ReheatSimulation();
    }
  };

  // Background Click Handler
  const handleBackgroundClick = (event) => {
    setContextMenu(null);

    if (activeSpawnType && graphRef.current && typeof graphRef.current.screen2GraphCoords === 'function') {
      // Coordinate transformation
      const coords = graphRef.current.screen2GraphCoords(event.clientX, event.clientY);
      const labelInput = prompt(`Enter manual label for ${activeSpawnType.toUpperCase()}:`);
      
      if (labelInput) {
        const timestamp = Date.now();
        const newNodeId = `manual-node-${timestamp}`;
        
        const iconMap = { domain: '🌐', ip: '🖥️', email: '✉️', phone: '📱' };
        const colorMap = { domain: '#a855f7', ip: '#ef4444', email: '#22d3ee', phone: '#eab308' };

        const newNode = {
          id: newNodeId,
          label: labelInput,
          group: 3,
          color: colorMap[activeSpawnType],
          icon: iconMap[activeSpawnType],
          x: coords.x,
          y: coords.y,
          fx: layoutMode === 'organic' ? null : coords.x,
          fy: layoutMode === 'organic' ? null : coords.y
        };

        const newLinks = [];
        if (selectedNode) {
          newLinks.push({ source: selectedNode.id, target: newNodeId });
        }

        setGraphState(prev => ({
          nodes: [...prev.nodes, newNode],
          links: [...prev.links, ...newLinks]
        }));

        hudAudio.playSuccess();
      }
      setActiveSpawnType(null);
    }
  };

  // Neighborhood Highlight Memo helper safely
  const { highlightNodes, highlightLinks } = useMemo(() => {
    const hNodes = new Set();
    const hLinks = new Set();
    const linksList = graphState.links || [];

    if (hoverNode) {
      hNodes.add(hoverNode.id);
      linksList.forEach(link => {
        const sourceId = typeof link.source === 'object' ? link.source.id : link.source;
        const targetId = typeof link.target === 'object' ? link.target.id : link.target;
        
        if (sourceId === hoverNode.id) {
          hNodes.add(targetId);
          hLinks.add(link);
        } else if (targetId === hoverNode.id) {
          hNodes.add(sourceId);
          hLinks.add(link);
        }
      });
    }
    return { highlightNodes: hNodes, highlightLinks: hLinks };
  }, [hoverNode, graphState.links]);

  // Node Canvas Painter (Safe from NaN and Division-by-Zero)
  const nodeCanvasObject = (node, ctx, globalScale) => {
    if (!node) return;
    const isRoot = node.group === 1;
    const isModule = node.group === 2;
    const isSelected = selectedNode && selectedNode.id === node.id;
    const isBulkSelected = node.id ? selectedNodeIds.has(node.id) : false;
    const isNodeLoading = node.id ? loadingNodeIds.has(node.id) : false;

    const hasFocus = hoverNode !== null;
    const isFocused = !hasFocus || (node.id && highlightNodes.has(node.id));

    const currentScale = globalScale || 1; // Safely guards canvas division by zero

    ctx.save();
    ctx.globalAlpha = isFocused ? 1.0 : 0.15;

    // Glowing border on hover/selection
    if (isSelected || isBulkSelected || (hoverNode && hoverNode.id === node.id)) {
      ctx.shadowColor = isBulkSelected ? '#22d3ee' : node.color || '#22d3ee';
      ctx.shadowBlur = isBulkSelected ? 24 : 18;
    }

    // Spinning Node Loader safely scaled
    if (isNodeLoading) {
      ctx.beginPath();
      const rAngle = (performance.now() / 200) % (Math.PI * 2);
      ctx.arc(node.x, node.y, isRoot ? 26 : isModule ? 20 : 12, rAngle, rAngle + Math.PI * 1.5);
      ctx.lineWidth = 1.8 / currentScale;
      ctx.strokeStyle = '#a855f7';
      ctx.stroke();
    }

    if (isRoot) {
      ctx.beginPath();
      ctx.arc(node.x, node.y, 22, 0, 2 * Math.PI);
      ctx.fillStyle = '#0a0a14';
      ctx.fill();
      ctx.lineWidth = isSelected ? 3.5 : 2.5;
      ctx.strokeStyle = '#22d3ee';
      ctx.stroke();
      ctx.shadowBlur = 0;
      ctx.font = '14px sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText('🎯', node.x, node.y);
      ctx.font = '700 10px Inter, sans-serif';
      ctx.fillStyle = '#ffffff';
      ctx.fillText(node.label || '', node.x, node.y + 34);
    } else if (isModule) {
      const w = 112, h = 30;
      const x = node.x - w / 2, y = node.y - h / 2;
      ctx.beginPath();
      ctx.roundRect(x, y, w, h, 8);
      ctx.fillStyle = '#0d0d18';
      ctx.fill();
      ctx.lineWidth = isSelected ? 2.5 : 1.4;
      ctx.strokeStyle = node.color;
      ctx.stroke();
      ctx.shadowBlur = 0;
      ctx.font = '11px sans-serif';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      ctx.fillText(node.icon || '', x + 8, node.y);
      ctx.font = '700 9px Inter, sans-serif';
      ctx.fillStyle = '#f1f5f9';
      ctx.fillText(node.label || '', x + 25, node.y);
    } else {
      ctx.font = '500 8px Inter, sans-serif';
      const tw = ctx.measureText(node.label || '').width;
      const w = tw + 14, h = 16;
      const x = node.x - w / 2, y = node.y - h / 2;
      ctx.beginPath();
      ctx.roundRect(x, y, w, h, 5);
      ctx.fillStyle = 'rgba(10, 10, 20, 0.85)';
      ctx.fill();
      ctx.lineWidth = isSelected || isBulkSelected ? 1.8 : 1;
      ctx.strokeStyle = isSelected || isBulkSelected ? '#22d3ee' : (node.color || '#475569') + '80';
      ctx.stroke();
      ctx.fillStyle = isSelected || isBulkSelected ? '#ffffff' : '#cbd5e1';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(node.label || '', node.x, node.y);
    }

    // Annotation Flags & Notes rendering
    const anno = node.id ? annotations[node.id] : null;
    if (anno) {
      if (anno.flag) {
        ctx.shadowBlur = 0;
        ctx.font = '12px sans-serif';
        ctx.fillText(anno.flag, node.x + (isRoot ? 16 : 12), node.y - (isRoot ? 16 : 10));
      }

      if (anno.note && hoverNode && hoverNode.id === node.id) {
        ctx.shadowBlur = 0;
        ctx.font = '7px monospace';
        const noteW = ctx.measureText(anno.note).width + 10;
        
        ctx.beginPath();
        ctx.roundRect(node.x - noteW / 2, node.y - (isRoot ? 42 : 32), noteW, 11, 4);
        ctx.fillStyle = 'rgba(7, 7, 14, 0.95)';
        ctx.strokeStyle = '#22d3ee';
        ctx.lineWidth = 0.8;
        ctx.fill();
        ctx.stroke();

        ctx.fillStyle = '#22d3ee';
        ctx.textAlign = 'center';
        ctx.fillText(anno.note, node.x, node.y - (isRoot ? 34 : 24));
      }
    }

    ctx.restore();
  };

  const handleNodeClick = (node, event) => {
    hudAudio.playClick();

    if (event.shiftKey) {
      // Toggle Shift multiselect
      setSelectedNodeIds(prev => {
        const next = new Set(prev);
        if (next.has(node.id)) {
          next.delete(node.id);
        } else {
          next.add(node.id);
        }
        return next;
      });
    } else {
      setSelectedNodeIds(new Set());
      setSelectedNode(node);
    }
  };

  // Bulk / Context actions engine
  const executeContextAction = (actionType) => {
    if (!contextMenu || !contextMenu.node) return; // Strict Context Check
    const targetNodes = selectedNodeIds.size > 0 ? Array.from(selectedNodeIds) : [contextMenu.node.id];
    setContextMenu(null);
    
    setLoadingNodeIds(prev => {
      const next = new Set(prev);
      targetNodes.forEach(id => next.add(id));
      return next;
    });
    hudAudio.playSweep();

    setTimeout(() => {
      const generatedNodes = [];
      const generatedLinks = [];

      targetNodes.forEach((nodeId, idx) => {
        const originalNode = graphState.nodes.find(n => n.id === nodeId);
        if (!originalNode) return;

        const timestamp = Date.now() + idx;
        const offsetVal = 35;

        if (actionType === 'dns') {
          const ipId = `dyn-dns-${timestamp}`;
          generatedNodes.push({
            id: ipId,
            label: `Resolved IP: 185.101.${Math.floor(Math.random() * 254)}.${Math.floor(Math.random() * 254)}`,
            group: 3,
            color: '#ef4444',
            icon: '🖥️',
            x: originalNode.x + (Math.random() - 0.5) * offsetVal,
            y: originalNode.y + (Math.random() - 0.5) * offsetVal
          });
          generatedLinks.push({ source: nodeId, target: ipId });
        } else if (actionType === 'whois') {
          const whoisId = `dyn-whois-${timestamp}`;
          generatedNodes.push({
            id: whoisId,
            label: `Passive WHOIS Registry Record`,
            group: 3,
            color: '#a855f7',
            icon: '📄',
            x: originalNode.x + (Math.random() - 0.5) * offsetVal,
            y: originalNode.y + (Math.random() - 0.5) * offsetVal
          });
          generatedLinks.push({ source: nodeId, target: whoisId });
        }
      });

      setGraphState(prev => ({
        nodes: [...prev.nodes, ...generatedNodes],
        links: [...prev.links, ...generatedLinks]
      }));

      setLoadingNodeIds(new Set());
      setSelectedNodeIds(new Set());
      hudAudio.playSuccess();
    }, 1200);
  };

  const handleFlagNode = (flagChar) => {
    if (!contextMenu || !contextMenu.node) return;
    const nodeId = contextMenu.node.id;
    setAnnotations(prev => ({
      ...prev,
      [nodeId]: { ...prev[nodeId], flag: flagChar }
    }));
    setContextMenu(null);
    hudAudio.playSuccess();
  };

  const handleAddNote = () => {
    if (!contextMenu || !contextMenu.node) return;
    const nodeId = contextMenu.node.id;
    const currentNote = annotations[nodeId]?.note || '';
    const noteVal = prompt('Enter analyst annotations for this entity:', currentNote);
    
    if (noteVal !== null) {
      setAnnotations(prev => ({
        ...prev,
        [nodeId]: { ...prev[nodeId], note: noteVal }
      }));
    }
    setContextMenu(null);
    hudAudio.playSuccess();
  };

  const renderContextMenu = () => {
    if (!contextMenu) return null;

    const node = contextMenu.node;
    const isBulk = selectedNodeIds.size > 0;

    return (
      <div 
        className="absolute bg-[#080812]/95 backdrop-blur-md border border-white/10 rounded-xl p-1 shadow-2xl z-[300] w-52 font-mono text-[9px] shadow-black/80 animate-fade-in"
        style={{ top: contextMenu.y, left: contextMenu.x }}
      >
        <div className="text-gray-500 px-2 py-1 border-b border-white/5 uppercase font-bold text-[8px] tracking-wider">
          {isBulk ? `// Bulk Actions (${selectedNodeIds.size} Nodes)` : `// Actions: ${node.label ? node.label.slice(0, 16) : ''}`}
        </div>

        <button 
          onClick={() => executeContextAction('dns')}
          className="w-full text-left px-2 py-1.5 hover:bg-cyan-500/10 hover:text-cyan-400 text-gray-300 rounded transition cursor-pointer flex items-center gap-1.5"
        >
          🌐 Run passive DNS resolution
        </button>
        <button 
          onClick={() => executeContextAction('whois')}
          className="w-full text-left px-2 py-1.5 hover:bg-purple-500/10 hover:text-purple-400 text-gray-300 rounded transition cursor-pointer flex items-center gap-1.5"
        >
          📄 Query registry WHOIS
        </button>

        {!isBulk && (
          <>
            <div className="border-t border-white/5 my-1" />
            <div className="text-gray-500 px-2 py-0.5 uppercase font-bold text-[7px] tracking-wider">
              // Investigator Tools
            </div>
            <button 
              onClick={handleAddNote}
              className="w-full text-left px-2 py-1 hover:bg-emerald-500/10 hover:text-emerald-400 text-gray-300 rounded transition cursor-pointer flex items-center gap-1.5"
            >
              📝 Add Custom Note
            </button>
            <div className="flex justify-around py-1 px-1 border-t border-white/5 mt-1.5">
              <button onClick={() => handleFlagNode('🚩')} className="hover:scale-125 transition cursor-pointer" title="Flag Critical">🚩</button>
              <button onClick={() => handleFlagNode('⚠️')} className="hover:scale-125 transition cursor-pointer" title="Flag Warning">⚠️</button>
              <button onClick={() => handleFlagNode('🟢')} className="hover:scale-125 transition cursor-pointer" title="Flag Safe">🟢</button>
              <button onClick={() => handleFlagNode(null)} className="text-[8px] text-red-400 hover:underline cursor-pointer" title="Clear Flag">✕</button>
            </div>
          </>
        )}

        <div className="border-t border-white/5 my-1" />
        <button 
          onClick={() => { setContextMenu(null); setSelectedNodeIds(new Set()); }}
          className="w-full text-left px-2 py-1 text-red-400 hover:bg-red-500/5 rounded transition cursor-pointer"
        >
          ✕ Close Action Menu
        </button>
      </div>
    );
  };

  const selectAndFocusNode = (node) => {
    setSelectedNode(node);
    setSearchQuery('');
    setShowSearchDropdown(false);
    if (graphRef.current && typeof graphRef.current.centerAt === 'function') {
      graphRef.current.centerAt(node.x, node.y, 1000);
      graphRef.current.zoom(2.5, 1000);
    }
  };

  const searchResults = useMemo(() => {
    if (!searchQuery) return [];
    const nodeList = graphState.nodes || [];
    return nodeList.filter(n => 
      n.label && typeof n.label === 'string' && n.label.toLowerCase().includes(searchQuery.toLowerCase())
    ).slice(0, 5);
  }, [searchQuery, graphState.nodes]);

  // Sidebar Analyst Inspector
  const renderIntelligenceDrawer = () => {
    if (!selectedNode) return null;

    const isRoot = selectedNode.group === 1;
    const isModule = selectedNode.group === 2;
    const isFinding = selectedNode.group === 3;
    const severity = getSeverity(selectedNode.label);

    const getSeverityStyles = (sev) => {
      if (sev === 'HIGH') return 'text-red-400 bg-red-500/10 border-red-500/20';
      if (sev === 'INFO') return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
      return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20';
    };

    return (
      <div className="absolute top-12 right-3 bottom-3 w-80 bg-[#07070d]/95 backdrop-blur-md border border-white/10 rounded-xl p-4 flex flex-col justify-between overflow-y-auto z-[210] animate-slide-in shadow-2xl shadow-black">
        <div>
          <div className="flex items-center justify-between border-b border-white/5 pb-3 mb-4">
            <span className="text-[10px] font-bold text-cyan-400 tracking-widest uppercase">
              // CyberXRecon Analyst Inspector
            </span>
            <button 
              onClick={() => setSelectedNode(null)} 
              className="text-gray-400 hover:text-white transition text-xs cursor-pointer"
            >
              ✕
            </button>
          </div>

          <div className="mb-4">
            <span className="text-[10px] text-gray-500 block mb-1">SELECTED ENTITY</span>
            <div className="flex items-center gap-2">
              <span className="text-lg">{selectedNode.icon || '🔍'}</span>
              <h4 className="text-sm font-bold text-white break-all">{selectedNode.label || ''}</h4>
            </div>
          </div>

          <div className="space-y-4">
            {isRoot && (
              <div className="space-y-2 text-xs">
                <div className="bg-white/5 p-2.5 rounded-lg border border-white/5">
                  <span className="text-gray-400 block mb-1">Target Host</span>
                  <span className="font-mono text-cyan-300 font-semibold">{target}</span>
                </div>
              </div>
            )}

            {isModule && (
              <div className="space-y-2 text-xs">
                <div className="bg-white/5 p-2.5 rounded-lg border border-white/5">
                  <span className="text-gray-400 block mb-1">Module Objective</span>
                  <p className="text-gray-300 italic leading-relaxed">
                    Analyzing active intelligence points mapped through CyberXRecon pipelines.
                  </p>
                </div>
              </div>
            )}

            {isFinding && (
              <div className="space-y-3 text-xs">
                <div>
                  <span className="text-gray-500 block text-[10px] mb-1">THREAT MATRIX</span>
                  <span className={`px-2.5 py-0.5 rounded border text-[9px] font-bold tracking-wider ${getSeverityStyles(severity)}`}>
                    {severity} RISK
                  </span>
                </div>
                <div className="bg-white/5 p-2.5 rounded-lg border border-white/5">
                  <span className="text-gray-400 block mb-1">Raw Evidence</span>
                  <span className="font-mono text-cyan-300 break-words font-semibold">{selectedNode.label || ''}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="border-t border-white/5 pt-3 mt-4">
          <button 
            onClick={() => alert(`Initiating secondary passive trace on: ${selectedNode.label}`)}
            className="w-full py-2 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/20 rounded-lg text-xs font-bold transition uppercase tracking-wider cursor-pointer"
          >
            🚀 Run Deep Trace
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="relative bg-black/50 backdrop-blur-md border border-white/10 rounded-2xl overflow-hidden flex flex-col min-h-0">
      
      {/* Header and Layout Toolbar */}
      <div className="px-4 py-2.5 border-b border-white/10 flex flex-col md:flex-row items-start md:items-center justify-between gap-3 shrink-0 bg-black/40 z-[220]">
        
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <span className="text-cyan-400">🕸️</span>
            <h3 className="text-xs font-bold uppercase tracking-wider text-white">Entity Relationship Map</h3>
          </div>

          {/* Dynamic Physics Layouts */}
          <div className="flex items-center gap-1 border border-white/5 bg-[#080810] p-0.5 rounded-lg text-[9px] font-mono">
            {['organic', 'hierarchical', 'circular'].map((mode) => (
              <button
                key={mode}
                onClick={() => handleLayoutChange(mode)}
                className={`px-2 py-0.5 rounded transition uppercase font-semibold cursor-pointer ${
                  layoutMode === mode 
                    ? 'bg-cyan-500/20 text-cyan-400 font-bold' 
                    : 'text-gray-500 hover:text-white'
                }`}
              >
                {mode}
              </button>
            ))}
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap items-center gap-2 text-[10px]">
          <span className="text-gray-500">FILTER:</span>
          {['ALL', 'HIGH', 'LOW', 'INFO'].map((f) => (
            <button
              key={f}
              onClick={() => setThreatFilter(f)}
              className={`px-2 py-0.5 rounded border font-semibold uppercase transition cursor-pointer ${
                threatFilter === f 
                  ? 'bg-cyan-500/20 border-cyan-500/40 text-cyan-400 font-bold' 
                  : 'bg-white/5 border-white/5 text-gray-400 hover:text-white'
              }`}
            >
              {f}
            </button>
          ))}
        </div>

        {/* Search */}
        <div className="relative w-full md:w-52">
          <input
            type="text"
            placeholder="🔍 Locate Entity..."
            value={searchQuery}
            onChange={(e) => {
              setSearchQuery(e.target.value);
              setShowSearchDropdown(true);
            }}
            onFocus={() => setShowSearchDropdown(true)}
            className="w-full bg-[#0d0d18] border border-white/10 focus:border-cyan-500/40 text-gray-200 rounded-lg px-3 py-1 text-xs outline-none transition"
          />
          {showSearchDropdown && searchResults.length > 0 && (
            <div className="absolute top-full left-0 right-0 mt-1 bg-[#090912] border border-white/10 rounded-lg shadow-2xl z-[230] overflow-hidden">
              {searchResults.map((node) => (
                <button
                  key={node.id}
                  onClick={() => selectAndFocusNode(node)}
                  className="w-full text-left px-3 py-1.5 hover:bg-cyan-500/10 text-xs border-b border-white/5 text-gray-300 hover:text-white flex items-center gap-2 cursor-pointer"
                >
                  <span>{node.icon || '📍'}</span>
                  <span className="truncate">{node.label || ''}</span>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
      
      {/* Canvas with Tools */}
      <div className="flex-1 relative min-h-0 flex">
        
        {/* Entity Spawner Palette */}
        <div className="w-12 bg-black/40 border-r border-white/5 flex flex-col items-center py-4 gap-4 shrink-0 z-20">
          <div className="text-[8px] font-mono text-gray-500 uppercase tracking-widest font-bold">// Tools</div>
          
          {['domain', 'ip', 'email', 'phone'].map((type) => {
            const icons = { domain: '🌐', ip: '🖥️', email: '✉️', phone: '📱' };
            const isActive = activeSpawnType === type;
            return (
              <button
                key={type}
                onClick={() => {
                  hudAudio.playClick();
                  setActiveSpawnType(isActive ? null : type);
                }}
                className={`w-8 h-8 rounded-lg flex items-center justify-center text-sm transition-all duration-150 cursor-pointer border ${
                  isActive 
                    ? 'bg-cyan-500/20 border-cyan-500/50 scale-110 animate-pulse text-white' 
                    : 'bg-[#080810]/80 border-white/5 text-gray-400 hover:text-white hover:border-white/15'
                }`}
                title={`Spawn Custom ${type.toUpperCase()}`}
              >
                {icons[type]}
              </button>
            );
          })}
          
          {activeSpawnType && (
            <div className="text-[6px] font-mono text-cyan-400 font-bold uppercase tracking-tighter text-center px-1 animate-pulse mt-2 leading-tight">
              Click Canvas to Place
            </div>
          )}
        </div>

        {/* --- CRASH-PROOF & ZERO-CLIPPING CANVAS CONTAINER --- */}
        <div ref={containerRef} className="flex-1 relative min-h-0">
          <ForceGraph2D
            ref={graphRef}
            width={dims.w} // Stretches perfectly to fill grid cell bounds
            height={dims.h}
            graphData={graphState}
            nodeCanvasObject={nodeCanvasObject}
            onNodeClick={handleNodeClick}
            onBackgroundClick={handleBackgroundClick}
            
            onNodeRightClick={(node, event) => {
              event.preventDefault();
              const rect = containerRef.current.getBoundingClientRect();
              
              if (!selectedNodeIds.has(node.id)) {
                setSelectedNode(node);
              }
              
              setContextMenu({
                x: event.clientX - rect.left,
                y: event.clientY - rect.top,
                node
              });
              hudAudio.playClick();
            }}
            onBackgroundRightClick={(event) => event.preventDefault()}
            
            onNodeHover={(node) => {
              setHoverNode(node || null);
              if (showSearchDropdown) setShowSearchDropdown(false);
            }}
            
            nodePointerAreaPaint={(node, color, ctx) => {
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(node.x, node.y, 22, 0, 2 * Math.PI);
              ctx.fill();
            }}
            backgroundColor="rgba(0,0,0,0)"
            
            linkColor={(link) => {
              const isHighlighted = highlightLinks.has(link);
              if (hoverNode) {
                return isHighlighted ? 'rgba(34, 211, 238, 0.8)' : 'rgba(255,255,255,0.015)';
              }
              return 'rgba(34, 211, 238, 0.12)';
            }}
            linkWidth={(link) => (highlightLinks.has(link) ? 2 : 1.2)}
            
            linkDirectionalParticles={(link) => {
              const isHighlighted = highlightLinks.has(link);
              if (hoverNode) {
                return isHighlighted ? 6 : 0;
              }
              return 3;
            }}
            linkDirectionalParticleWidth={2}
            linkDirectionalParticleSpeed={(link) => 
              highlightLinks.has(link) ? 0.012 : 0.005
            }
            
            d3AlphaDecay={0.4}
            cooldownTicks={100} // Settles beautifully on load
            enableZoom={true}
            enablePan={true}
          />

          {/* Context Menus */}
          {renderContextMenu()}

          {/* Sidebar Inspector */}
          {renderIntelligenceDrawer()}

          {/* Floating Controls */}
          <div className="absolute bottom-3 left-3 flex flex-col gap-1.5 z-10">
            <button 
              onClick={() => {
                if (graphRef.current && typeof graphRef.current.zoomToFit === 'function') {
                  graphRef.current.zoomToFit(400, 40);
                }
              }}
              className="w-8 h-8 flex items-center justify-center bg-[#07070d]/80 border border-white/10 hover:border-cyan-500/40 text-gray-400 hover:text-cyan-400 rounded-lg text-xs transition cursor-pointer"
              title="Recenter Camera"
            >
              🎯
            </button>
            <button 
              onClick={() => {
                if (graphRef.current && typeof graphRef.current.zoom === 'function') {
                  const currentZoom = graphRef.current.zoom();
                  graphRef.current.zoom(currentZoom + 0.4, 400);
                }
              }}
              className="w-8 h-8 flex items-center justify-center bg-[#07070d]/80 border border-white/10 hover:border-cyan-500/40 text-gray-400 hover:text-cyan-400 rounded-lg text-xs transition cursor-pointer font-bold"
              title="Zoom In"
            >
              ＋
            </button>
            <button 
              onClick={() => {
                if (graphRef.current && typeof graphRef.current.zoom === 'function') {
                  const currentZoom = graphRef.current.zoom();
                  graphRef.current.zoom(Math.max(0.5, currentZoom - 0.4), 400);
                }
              }}
              className="w-8 h-8 flex items-center justify-center bg-[#07070d]/80 border border-white/10 hover:border-cyan-500/40 text-gray-400 hover:text-cyan-400 rounded-lg text-xs transition cursor-pointer font-bold"
              title="Zoom Out"
            >
              －
            </button>
          </div>

          {/* Status Ticker */}
          {selectedNodeIds.size > 0 && (
            <div className="absolute bottom-3 right-3 bg-cyan-500/10 border border-cyan-500/30 px-3 py-1.5 rounded-lg text-[9px] font-mono text-cyan-300 animate-pulse pointer-events-none">
              [LOCKED MULTI-SECTOR: {selectedNodeIds.size} NODES ACTIVE // HOLD RIGHT-CLICK TO RUN AGGREGATE]
            </div>
          )}
        </div>

      </div>
    </div>
  );
}